config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories do 
     resources :deals 
     end
  # resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"
end

app/models/deal_category.rb
class DealCategory < ApplicationRecord
  belongs_to :category
  belongs_to :deal

  validates :category_id, presence: true
  validates :deal_id, presence: true
end

app/controllers/deal_categories_controller.rb
class DealCategoriesController < ApplicationController
  before_action :set_deal_category, only: %i[show edit update destroy]

  # GET /deal_categories or /deal_categories.json
  def index
    @deal_categories = DealCategory.all
  end

  # GET /deal_categories/1 or /deal_categories/1.json
  def show; end

  # GET /deal_categories/new
  def new
    @deal_category = DealCategory.new
  end

  # GET /deal_categories/1/edit
  def edit; end

  # POST /deal_categories or /deal_categories.json
  def create
    @deal_category = DealCategory.new(deal_category_params)

    respond_to do |format|
      if @deal_category.save
        format.html { redirect_to deal_category_url(@deal_category), notice: 'Deal category was successfully created.' }
        format.json { render :show, status: :created, location: @deal_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @deal_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deal_categories/1 or /deal_categories/1.json
  def update
    respond_to do |format|
      if @deal_category.update(deal_category_params)
        format.html { redirect_to deal_category_url(@deal_category), notice: 'Deal category was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @deal_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deal_categories/1 or /deal_categories/1.json
  def destroy
    @deal_category.destroy

    respond_to do |format|
      format.html { redirect_to deal_categories_url, notice: 'Deal category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_deal_category
    @deal_category = DealCategory.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def deal_category_params
    params.require(:deal_category).permit(:category_id, :deal_id)
  end
end

app/helpers/deal_categories_helper.rb
module DealCategoriesHelper
end

app/views/deal_categories/_deal_category.html.erb
<div id="<%= dom_id deal_category %>">
  <p>
    <strong>Category:</strong>
    <%= deal_category.category_id %>
  </p>

</div>

app/views/deal_categories/_form.html.erb
<%= form_with(model: deal_category) do |form| %>
  <% if deal_category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(deal_category.errors.count, "error") %> prohibited this deal_category from being saved:</h2>

      <ul>
        <% deal_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.label :deal_id, style: "display: block" %>
    <%= form.text_field :deal_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/deal_categories/edit.html.erb
<h1>Editing deal category</h1>

<%= render "form", deal_category: @deal_category %>

<br>

<div>
  <%= link_to "Show this deal category", @deal_category %> |
  <%= link_to "Back to deal categories", deal_categories_path %>
</div>

app/views/deal_categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Deal categories</h1>

<div id="deal_categories">
  <% @deal_categories.each do |deal_category| %>
    <%= render deal_category %>
  <% end %>
</div>

<%= link_to "New deal category", new_deal_category_path %>

app/views/deal_categories/new.html.erb
<h1>New deal category</h1>

<%= render "form", deal_category: @deal_category %>

<br>

<div>
  <%= link_to "Back to deal categories", deal_categories_path %>
</div>

app/views/deal_categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @deal_category %>

<div>
  <%= link_to "Edit this deal category", edit_deal_category_path(@deal_category) %> |
  <%= link_to "Back to deal categories", deal_categories_path %>

  <%= button_to "Destroy this deal category", @deal_category, method: :delete %>
</div>