config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories do 
     resources :deals 
     end
  # resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_many :deal_category, dependent: :destroy
  has_many :categories, through: :destroy

  validates :name, presence: true
  validates :amount, presence: true
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: %i[show edit update destroy]

  # GET /deals or /deals.json
  def index
    @category = Category.find(params[:category_id])
    # @deals = Deal.all
    @deal_category = DealCategory.all
    @deals = @category.deals.order(created_at: :desc)
    # @deals = DealCategory.includes(:deal).where(category_id: @category.id)
  end

  # GET /deals/1 or /deals/1.json
  def show; end

  # GET /deals/new
  def new
    @category = Category.find(params[:category_id])
    @deal = Deal.new
  end

  # GET /deals/1/edit
  def edit; end

  # POST /deals or /deals.json
  def create
    @deal = Deal.new(deal_params)
    @deal.author = current_user
    category_id = params[:category_id]
    puts category_id

    respond_to do |format|
      if @deal.save
        DealCategory.create(deal_id: @deal.id, category_id: category_id)
        format.html { redirect_to category_deals_path, notice: 'Deal was successfully created.' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1 or /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to deal_url(@deal), notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1 or /deals/1.json
  def destroy
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to deals_url, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_deal
    @deal = Deal.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def deal_params
    params.require(:deal).permit(:name, :amount)
  end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_deal.html.erb
<div id="<%= dom_id deal %>">

<div class="deal-box1">
  <p>
    <%= deal.name %>
  </p>

  <p>
    $<%= deal.amount %>
  </p>
</div>
</div>

app/views/deals/_form.html.erb
<%= form_with(model: deal, url: url, method: :post) do |form| %>
  <% if deal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
        <% deal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div form_divas>
    <%= form.text_field :name, required: true, placeholder: "Transaction Name", class: "login-field" %>
  </div>

  <div form_divas>
    <%= form.number_field :amount, placeholder: "Enter Amount", class: "login-field" %>
  </div>

  <div form_divas>
    <label class="name_label">Select category</label>
     <%= form.collection_select :category_id, Category.all, :id, :name, { include_blank: 'Select Category', selected: @category.id }, required: true, class:'' %>
 </div>


  <div class=''>
    <%= form.submit "Add transaction", class:"category_button" %>
  </div>
<% end %>

app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<%= render "form", deal: @deal %>

<br>

<div>
  <%= link_to "Show this deal", @deal %> |
  <%= link_to "Back to deals", deals_path %>
</div>

app/views/deals/index.html.erb
<%= render partial: 'shared/nav', locals: {title:'TRANSACTION', symbol:'←', url: categories_path} %>
<div class="total_box">

<h3><%= @category.name %></h3>
<p>$<%= @deals.sum {|deal| deal.amount} %></p>
</div>
<div id="deals">
  <% @deals.each do |deal| %>
    <%= render deal %>
  <% end %>
</div>

<button><%= link_to "Add a new transaction", new_category_deal_path, class: 'category_button fixed-bottom btn_category' %></button>

app/views/deals/new.html.erb
<%= render partial: 'shared/nav', locals: {title: 'Add a new transcation', symbol:'←', url: category_deals_path}%>

<%= render "form", deal: @deal, url: category_deals_path %>

app/views/deals/show.html.erb
<%= render @deal %>

<div>
  <%= link_to "Edit this deal", edit_deal_path(@deal) %> |
  <%= link_to "Back to deals", deals_path %>

  <%= button_to "Destroy this deal", @deal, method: :delete %>
</div>