config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories do 
     resources :deals 
     end
  # resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_one_attached :icon
  has_many :deal_categories, dependent: :destroy
  has_many :deals, through: :deal_categories

  validates :name, presence: true
  validates :icon, presence: false

  def calculate_amount
    deals.sum { |deal| deal.amount.to_i }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.includes(:deals).where(author: current_user)
    # @total_deals = categories.joins(:deals).sum('deals.amount')
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    name = params[:name]
    icon = params[:icon]
    p name
    p icon
    @category = Category.new(category_params)
    puts current_user.id
    @category.author = current_user
    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <%= category.name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form_div">
      <% form.label :name  %>
      <%= form.text_field :name, placeholder: "Category Name", class: "login-field"%>
      <% form.object.errors.full_messages_for(:name).each do |message|%>
      <div><%= message %></div>
      <%end%>
    </div>
      <br>
     <div class="form_diva">
    <%= form.label :icon, 'Chose icon:', class: 'labela' %><br>
      <%= form.file_field :icon, class: "chose-icon" %>
        <% form.object.errors.full_messages_for(:icon).each do |message|%>
        <div><%= message %></div>
        <%end%>
     </div>
     <br>
      <%= form.submit "Create Category", class:"category_button"%>
    </div>
<%end%>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<%= render partial: 'shared/nav', locals: {title: 'Categories', symbol:'', url: ''}%>
 
<% @categories.each do |category| %>
    <div class='deal'>
        <div class="deal-box">
      <div>
      <%= image_tag category.icon, class: 'category_icon' %> 
      </div>
           
     <div class="category-cart">
     <div class="category-details">
        <h3 class='category_name'>
          <%= link_to category.name, category_deals_path(category.id) %>
         </h3>     
        <p>$<%= category.calculate_amount %></p>
     </div>
     <p><%= category.created_at.strftime("%d %b %Y") %></p>
    </div>
    </div>
   
  <% end %>


<button><%= link_to "Add New category", new_category_path, class: 'category_button fixed-bottom btn_category' %></button>

app/views/categories/new.html.erb
<%= render partial: 'shared/nav', locals: {title:'Categories', symbol:'←', url: :back}%>


<%= render "form", category: @category %>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>